Traceback (most recent call last):
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = 1, 2, 3
x [0] = '12' # la modification d'un t-uple n'est pas permise
print (x)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[21], line 2[0m
[1;32m      1[0m x [38;5;241m=[39m [38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m
[0;32m----> 2[0m [43mx[49m[43m [49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m [38;5;241m=[39m [38;5;124m'[39m[38;5;124m12[39m[38;5;124m'[39m [38;5;66;03m# la modification d'un t-uple n'est pas permise[39;00m
[1;32m      3[0m [38;5;28mprint[39m (x)

[0;31mTypeError[0m: 'tuple' object does not support item assignment

