Traceback (most recent call last):
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/scola/Maintenance/jupyter-book/jupyterbookenv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print (1 in (0, 1, 2, 3, 4, 5))
print (6 in [0, 1, 2, 3, 4, 5])
print ('janvier' in jours_dans_le_mois)
print (31 in jours_dans_le_mois)
------------------

----- stdout -----
True
False
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m [38;5;28mprint[39m ([38;5;241m1[39m [38;5;129;01min[39;00m ([38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m, [38;5;241m4[39m, [38;5;241m5[39m))
[1;32m      2[0m [38;5;28mprint[39m ([38;5;241m6[39m [38;5;129;01min[39;00m [[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m, [38;5;241m4[39m, [38;5;241m5[39m])
[0;32m----> 3[0m [38;5;28mprint[39m ([38;5;124m'[39m[38;5;124mjanvier[39m[38;5;124m'[39m [38;5;129;01min[39;00m [43mjours_dans_le_mois[49m)
[1;32m      4[0m [38;5;28mprint[39m ([38;5;241m31[39m [38;5;129;01min[39;00m jours_dans_le_mois)

[0;31mNameError[0m: name 'jours_dans_le_mois' is not defined

